use_frameworks!

target 'MCUtility_Example' do
  pod 'MCUtility', :path => '../'

  target 'MCUtility_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
